version = "1.0"

[main]

####################
#### ACCOUNTS CONFIG
####################

    [main.target]

    name = "Target config"

    help = "Config destination servers"

        [main.target.target_servers]
        ask.en = "Edit the target servers"
        ask.fr = "Editez les serveurs destinations"
        bind = "/etc/nginx/conf.d/__DOMAIN__.d/upstream.conf.inc"
        default = "server 127.0.0.1;"
        help.en = "One serveur per line starting with 'server ' ending with ';'. Read the manual for more options : https://nginx.org/en/docs/http/ngx_http_upstream_module.html"
        help.fr = "Un serveur par ligne commençant par 'server ' terminant par ';'. Lire la documentation pour plus d'option : https://nginx.org/en/docs/http/ngx_http_upstream_module.html"
        type = "text"

        [main.target.target_protocol]
        ask.en = "Are servers have http or https access ?"
        ask.fr = "Les serveurs sont ils accessibles en https ou en http ?"
        bind = null
        type = "select"
        choices = ["http", "https"]
        default = "http"
