version = "1.0"

[main]

####################
#### ACCOUNTS CONFIG
####################

    [main.target]

    name = "Target config"

    help = "Config destination servers"

        [main.target.servers]
        ask.en = "Edit the target"
        ask.fr = "Editez les destinations"
        bind = "/etc/nginx/conf.d/__DOMAIN__.d/upstream.conf.inc"
        default = "127.0.0.1"
        help.en = "Edit the target"
        help.fr = "Editez les destinations"
        type = "text"


