version = "1.0"

[main]

services = [ "__APP__" ]

name.en = "Config panel"
name.fr = "Panneau de configuration"

help = "Here you can easily configure some things about your redirect."

####################
#### ACCOUNTS CONFIG
####################

    [main.target]
    ask.en = "Edit the target"
    ask.fr = "Editez les destinations"
    default = "127.0.0.1"
    help.en = "Edit the target"
    help.fr = "Editez les destinations"
    type = "text"


