#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# BACKUP THE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Ensure downward compatibility..."
if [[ "${redirect_type:-}" == *"proxy"* ]]; then
    redirect_type="reverseproxy"
fi

if [[ "${redirect_type:-}" == "reverseproxy" || "${redirect_type:-}" == "passthrough" ]]; then
  ynh_backup "/etc/nginx/conf.d/${domain}.d/upstream.conf.inc"
  ynh_backup "/etc/nginx/conf.d/${domain}.d/${app}.conf"
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
