#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

mv ../conf/{"nginx-$redirect_type.conf",nginx.conf}
ynh_config_change_url_nginx
ynh_config_add --template="upstream.config" --destination="/etc/nginx/conf.d/${domain}.d/upstream.config"
ynh_replace --match=';' --replace=';
server ' --file="/etc/nginx/conf.d/${domain}.d/upstream.config"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
