#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

mv ../conf/{"nginx-$redirect_type.conf",nginx.conf}
ynh_config_change_url_nginx
ynh_config_add --template="upstream.conf.inc" --destination="/etc/nginx/conf.d/${domain}.d/upstream.conf.inc"
ynh_replace_regex --match=";(?=[^\r\n\t\f\v ])" --replace=";\nserver " --file="/etc/nginx/conf.d/${domain}.d/upstream.conf.inc"


#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
