#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# REDIRECT GET/SET
#=================================================

get__target_protocol() {
    return $(cat "/etc/nginx/conf.d/adm.grg.3cmr.fr.d/redirect__4.conf" | grep -Eo 'proxy_pass\s*([a-z]*)'| grep -Eo '([a-z]*)$')
}

set__target_protocol() {
    $(sed -i -E "s/proxy_pass\s*([a-z]*)/proxy_pass $target_protocol/g" "/etc/nginx/conf.d/${domain}.d/${app}.conf")
}

#=================================================

ynh_app_config_run "$1"
