#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#_validate_redirect_uri

#=================================================
# CONFIGURE NGINX
#=================================================
ynh_script_progression "Configuring NGINX web server..."

mv ../conf/{"nginx-$redirect_type.conf",nginx.conf}

if [[ "${redirect_type:-}" == *"proxy"* ]]; then
  ynh_config_add --template="upstream.conf.inc" --destination="/etc/nginx/conf.d/${domain}.d/upstream.conf.inc"
  cp -R "../conf/hook_conf_regen" "/usr/share/yunohost/hooks/conf_regen/98-nginx_$app"
fi

yunohost tools regen-conf nginx


#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
