#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#_validate_redirect_uri

#=================================================
# CONFIGURE NGINX
#=================================================
ynh_script_progression "Configuring NGINX web server..."

mv ../conf/{"nginx-$redirect_type.conf",nginx.conf}
ynh_config_add_nginx

ynh_config_add --template="upstream.config" --destination="/etc/nginx/conf.d/${domain}.d/upstream.config"
ynh_replace_regex --match=";(?=[^\r\n\t\f\v ])" --replace=";\nserver " --file="/etc/nginx/conf.d/${domain}.d/upstream.config"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
