#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================

ynh_config_remove_nginx
# do not remove if domain not removed
# ynh_safe_rm "/etc/nginx/conf.d/${domain}.d/upstream.conf.inc"
#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
