#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================

ynh_config_remove_nginx
ynh_safe_rm /etc/nginx/$domain.d/upstream.config
#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
