#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================

if [[ "${redirect_type:-}" == *"proxy"* ]]; then
    redirect_type="reverseproxy"
else
    redirect_type="redirect"
fi
ynh_app_setting_set --key='redirect_type' --value=$redirect_type

if [[ -z "${target:-}" ]] && [[ -n "${redirect_path:-}" ]]; then
    target="$redirect_path"
    ynh_app_setting_delete --key=redirect_path
fi
if [[ $target ]]; then
    new_target = $(sed -i -e "s/([01]*[0-9]*[0-9]\.[01]*[0-9]*[0-9]\.[01]*[0-9]*[0-9]\.[01]*[0-9]*[0-9])/m" $target)
    new_protocol = $(sed -i -e "s/(.*):\/\/.*/m" $target)
    ynh_app_setting_set_default --key='protocol' --value=$new_protocol
    ynh_app_setting_set_default --key='servers' --value="server "$new_target";"
fi

ynh_app_setting_set_default --key='protocol' --value="http"
ynh_app_setting_set_default --key='servers' --value="server 127.0.0.1;"
ynh_app_setting_delete --key=target
#=================================================
# CONFIGURE NGINX
#=================================================
ynh_script_progression "Configuring NGINX web server..."

# make proxy load balancing working with upstrem config. 
ynh_config_add --template="upstream.conf.inc" --destination="/etc/nginx/conf.d/${domain}.d/upstream.conf.inc"

mv ../conf/{nginx-$redirect_type.conf,nginx.conf}
ynh_config_add_nginx

ynh_script_progression "Upgrade of $app completed"
