#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================

if [[ "${redirect_type:-}" == *"proxy"* ]]; then
    redirect_type="reverseproxy"
else
    redirect_type="redirect"
fi
ynh_app_setting_set --key='redirect_type' --value=$redirect_type

if [[ -z "${target_servers:-}" ]] && [[ -n "${target:-}" ]]; then
    target_servers="$target"
    ynh_app_setting_delete --key=target
    new_target_servers=$(echo $target_servers | grep -Eo '(([0-9]{1,3}\.){3}[0-9]{1,3}(:[0-9]{0,5})?)|(([a-z0-9]*\.){1,5}[a-z]*(:[0-9]{0,5})?)')
    new_target_protocol=$(echo $target_servers | grep -Eo '([a-z]*):'| grep -Eo '([a-z]*)')
    ynh_app_setting_set_default --key='target_protocol' --value=$new_target_protocol
    ynh_app_setting_set_default --key='target_servers' --value="server "$new_target_servers";"
fi

ynh_app_setting_set_default --key='target_protocol' --value="http"
ynh_app_setting_set_default --key='target_servers' --value="server 127.0.0.1;"
#=================================================
# CONFIGURE NGINX
#=================================================
ynh_script_progression "Configuring NGINX web server..."

# make proxy load balancing working with upstrem config. 
ynh_config_add --template="upstream.conf.inc" --destination="/etc/nginx/conf.d/${domain}.d/upstream.conf.inc"

mv ../conf/{nginx-$redirect_type.conf,nginx.conf}
ynh_config_add_nginx

ynh_script_progression "Upgrade of $app completed"
